version: "1.0"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
  redis:
    image: redis
    ports:
      - 6379:6379